version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/da-tre-fn-dlq-slack-alerts"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/da-tre-fn-dlq-slack-alerts"
    schedule:
      interval: "daily"
